version: "3"
services:
  app:
    container_name: eventemitter
    restart: always
    build: ./
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongocontainer
    image: mongo
    ports:
      - "27017:27017"